- hosts: target
  become: True
  become_user: root
  tasks:
    - name: Install Nginx
      apt:
        name: nginx
        state: present

    - name: Creating a file with hello world content
      lineinfile:
        path: "/var/www/html/index.html"
        line: "Hello, World!"
        create: True
        
    - name: Enable default Nginx website
      file:
        src: /etc/nginx/sites-available/default
        path: /etc/nginx/sites-enabled/default
        state: link

    - name: Restart Nginx
      service:
        name: nginx
        state: restarted
    
